services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Api\Behat\Context\FeatureContext:
    public: true
    arguments:
      $kernel: "@kernel"

  Ivoz\Api\Behat\Extension\FixerFormatter\FixerFormatterExtension:
    public: true
    arguments:
      $kernel: "@kernel"

