services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Behatch\HttpCall\Request: ~

  Ivoz\Api\Behat\Context\FeatureContext:
    public: true
    arguments:
      $kernel: "@kernel"
